version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app  # Optional: For live reloading in development
      - frontend_node_modules:/app/node_modules
      - /app/dist

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app  # Optional: For live reloading in development
      - backend_node_modules:/app/node_modules

volumes:
  frontend_node_modules:
  backend_node_modules:
